### ISSUE TITLE
custom command 

### ISSUE THREAD

**Issue by llronaldoll** [jackthehack21/BlockReward#1]
is it possible to add custom commands to get items made by other plugins?

**Comment by JaxkDev** [comment]
Sorry I stopped maintaining this as I didn’t know people used it, but I am willing to work on your suggestion if it’s a easy addition.

By custom commands what do you mean ?

**Comment by llronaldoll** [comment]
Good morning, I use the https://github.com/JackMD/MysteryCrate plugin and it uses some command to give some different keys to the players, I would like that when breaking a block or killing an entity, the key was dropped

**Comment by JaxkDev** [comment]
Ok thanks for the link, I’ll talk to him and take a quick look through how his items are made but it should be possible, I’ll get to this as soon as I have time most likely in 20hours as I am working on a new plugin today if you do have any more questions you can post them and re open the issue but for now:

In the next major update there may be other custom items in the plugin keep a eye out on the releases (DO not download source code as it is most likely broken)
